### ISSUE TITLE
GalsimFiberlossCalculator has dropped the fiber_placement argument

### ISSUE THREAD

**Issue by sybenzvi** [desihub/desidithering#4]
Several of the dithering examples in docs/nb depend on the fiber_placement argument in GalsimFiberlossCalculator to handle offsets between the source and fiber centers. This argument has been dropped from the constructor, breaking most of the examples. It should be possible to reproduce the original function using the offset parameter in the GalsimFiberlossCalculator "calculate" member function.

**Comment by sybenzvi** [comment]
Update: the fiber_placement is not an argument that was removed from specsim, but an addition made by @tolgayapici in the specsim dithering branch which hasn't been merged into the specsim master branch.

**Comment by tolgayapici** [comment]
thanks for reporting this. it is time for merging with the master anyway.
