### ISSUE TITLE
Missing files for desidithering/docs/nb notebooks

### ISSUE THREAD

**Issue by abigailkaplan** [desihub/desidithering#5]
Missing DESI-0347_noblur.ecsv: needed for dithering_exposure, dithering_randoms, and dithering_telescope 
Missed spectra needed for plot_star_spectra

**Comment by tolgayapici** [comment]
the spectra is the spectra distributed within the collaboration. i will add a link pointing to where is it on NERSC. I will also make a copy on bluehive if it is not there.

**Comment by tolgayapici** [comment]
the missing ecsv file is added to config but later it will be moved to a more proper directory.

I will leave the issue open until these are tested.

**Comment by tolgayapici** [comment]
since there are no missing files anymore. i am closing this issue. the spectra needed are in NERSC and Bluehive. the other file is committed into the project
